name: lora_wsi
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
      - pytorch-lightning==1.5.0
      - addict==2.4.0
      - pandas==1.5.3

