General:
    epochs: &epochs 200
    seed: 123456

Data:
    dataframe: "./splits/camelyon16_train_10fold.csv"
    test_df: "./splits/camelyon16_test.csv"
    feat_dir: "/your/dir/to/wsi_feature"
    batch_size: 1
    num_workers: 4
    label_dict: {"normal":0, "tumor":1}

Model:
    name: "models.DSMIL"
    params:
        feat_dim: 1024
        n_classes: 2

Optimizer:
    optimizer:
        name: Adam
        params:
            lr: 0.0001
            amsgrad: False
    lr_scheduler:
        name: CosineAnnealingLR
        params:
            T_max: *epochs
            last_epoch: -1

Loss:
    name: "CrossEntropyLoss"
    params:
        label_smoothing: 0.0